### ISSUE TITLE
关于体验

### ISSUE THREAD

**Issue by CoderMonkie** [Wensibob/Note#1]
首先，感谢作者分享。
目前还没做过安卓，仅仅来学习来看看。
试了一下该app，不错啊。
标星取消的时候，退出发现没改变，原来是要点保存。
这个在点击的时候时时反映不是很好吗，保存只针对note内容吧。
或者把标星也拿到侧滑里面，比如放到另一侧。

还有一点，挺奇怪的。。
原来置顶就是把时间改成最新啊。
稍感不妥，愚见为，先检索出属性为置顶的，按时间排，
在放非置顶的也按时间排。

**Comment by Wensibob** [comment]
感谢你的建议，之前在想置顶操作的时候没有考虑周全，你的这个建议十分不错，我会在下个版本继续改进；另外将加星弄成侧滑图标是个十分赞的建议，同样在下个版本会有所改进，非常感谢
